defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

paginate: 10
paginate_path: "/blog/page:num/"

title: Minho Kim, PhD
subtitle: ORISE SCINet Postdoctoral Fellow

left_side:
  background_image: "./assets/images/IMG_0826.png"
  background_color: "#484848"
  close_button_color: "#000000"
  text_color: "#FFFFFF"

footer:
  copyright_text: "&copy; Minho Kim"

# Side Menu Links
menu:
  - text: About
    link: /
    icon: ""

  - text: Publications
    link: /publications
    icon: ""

  - text: Media
    link: /media
    icon: ""

  #- text: Blog
  #  link: /blog
  #  icon: ""

  - text: CV (ver. 2024.11)
    link: "https://drive.google.com/file/d/1zUCcGg6qOHIk74BlLy2JrlRL2oUiZavW/view"
    icon: ""

  #- text: My Resume
  #  link: /resume
  #  icon: ""

  #- text: Blog Posts
  #  link: /blog
  #  icon: ""

# Socialmedia Icons
social_icons:
  - name: linkedin
    link: https://www.linkedin.com/in/minho-kim-328a23169
    icon: fab fa-linkedin

  - name: github
    link: https://github.com/Minho-Illini
    icon: fab fa-github-square

#   - name: facebook
#     link: https://www.facebook.com/christian.ezeani.cyb
#     icon: fab fa-facebook-square

#   - name: twitter
#     link: https://www.twitter.com/christianezeani
#     icon: fab fa-twitter
    
